# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import registry_pb2 as registry__pb2


class RegisterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.registerReplica = channel.unary_unary(
                '/Register/registerReplica',
                request_serializer=registry__pb2.registerReplicaRequest.SerializeToString,
                response_deserializer=registry__pb2.registerReplicaResponse.FromString,
                )
        self.GetReplicaList = channel.unary_unary(
                '/Register/GetReplicaList',
                request_serializer=registry__pb2.ClientRequest.SerializeToString,
                response_deserializer=registry__pb2.ClientResponse.FromString,
                )


class RegisterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def registerReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplicaList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegisterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'registerReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.registerReplica,
                    request_deserializer=registry__pb2.registerReplicaRequest.FromString,
                    response_serializer=registry__pb2.registerReplicaResponse.SerializeToString,
            ),
            'GetReplicaList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReplicaList,
                    request_deserializer=registry__pb2.ClientRequest.FromString,
                    response_serializer=registry__pb2.ClientResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Register', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Register(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def registerReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Register/registerReplica',
            registry__pb2.registerReplicaRequest.SerializeToString,
            registry__pb2.registerReplicaResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReplicaList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Register/GetReplicaList',
            registry__pb2.ClientRequest.SerializeToString,
            registry__pb2.ClientResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
