# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import server_pb2 as server__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eregistry.proto\x1a\x0cserver.proto\"*\n\x16registerServerResponse\x12\x10\n\x08response\x18\x01 \x01(\t\"0\n\x15registerServerRequest\x12\x17\n\x06server\x18\x01 \x01(\x0b\x32\x07.Server\"\x1f\n\rClientRequest\x12\x0e\n\x06\x63lient\x18\x01 \x01(\t\"/\n\x0e\x43lientResponse\x12\x1d\n\x0cserverclient\x18\x01 \x03(\x0b\x32\x07.Server\"O\n\x0eRegistryServer\x12\x18\n\x07servers\x18\x01 \x03(\x0b\x32\x07.Server\x12\x0b\n\x03N_r\x18\x02 \x01(\x05\x12\x0b\n\x03N_w\x18\x03 \x01(\x05\x12\t\n\x01N\x18\x04 \x01(\x05\x32\x83\x01\n\x08Register\x12\x43\n\x0eregisterServer\x12\x16.registerServerRequest\x1a\x17.registerServerResponse\"\x00\x12\x32\n\rGetServerList\x12\x0e.ClientRequest\x1a\x0f.ClientResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registry_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERSERVERRESPONSE._serialized_start=32
  _REGISTERSERVERRESPONSE._serialized_end=74
  _REGISTERSERVERREQUEST._serialized_start=76
  _REGISTERSERVERREQUEST._serialized_end=124
  _CLIENTREQUEST._serialized_start=126
  _CLIENTREQUEST._serialized_end=157
  _CLIENTRESPONSE._serialized_start=159
  _CLIENTRESPONSE._serialized_end=206
  _REGISTRYSERVER._serialized_start=208
  _REGISTRYSERVER._serialized_end=287
  _REGISTER._serialized_start=290
  _REGISTER._serialized_end=421
# @@protoc_insertion_point(module_scope)
